---
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: lamp1
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# device_tracker:
#   - platform: owntracks

#  - platform: nmap_tracker
#    hosts: 192.168.0.1/24
#    home_interval: 300
#    track_new_devices: false
#  - platform: owntracks

fan:
  - platform: mqtt
    name: "Greenhouse ventilation"
    qos: 1
    optimistic: false
    retain: true
    command_topic: "catingham_palace/greenhouse/ventilation/switch"
    state_topic: "catingham_palace/greenhouse/ventilation/status"

person:
  - name: Rubens
    id: rubens
    device_trackers:
      - device_tracker.rubens_phone
  - name: Valentina
    id: valentina
    device_trackers:
      - device_tracker.valentina_phone

media_player:
  - platform: samsungtv
    name: Living room TV
    host: !secret living_room_tv_ip
    mac: !secret living_room_tv_mac_address
    port: 8001

input_select:
  roller_shutters_scene:
    name: Roller shutters scene
    options:
      - "day"
      - "night"

google_assistant:
  project_id: catingham-palace
  service_account: !secret google_assistant_service_account
  entity_config:
    lock.driveway_gate:
      aliases:
        - cancello
        - cancellone
      room: Driveway
    lock.driveway_door:
      aliases:
        - cancelletto
      room: Driveway
    lock.stair_front_door:
      aliases:
        - porta
      room: Scale
    light.driveway_lights:
      aliases:
        - luci in giardino
        - luci nel vialetto
      room: Driveway
    light.entryway:
      room: Ingresso
    light.living_room_main:
      room: Sala
      name: Luce grande
      aliases:
        - luce principale
    light.kitchen_main:
      room: Cucina
      name: Luce grande
      aliases:
        - luce principale
    light.kitchen_hood:
      room: Cucina
      name: Luce della cappa
    light.kitchen_countertop:
      room: Cucina
      name: Luce piano cucina
      aliases:
        - luce sotto lavello
    light.green_room_desktop_light:
      room: Ufficio
      name: Luce scrivania

cast:
  tv_shut_down_delay:
    duration: 30

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: home

lovelace:
  mode: yaml

automation: !include ../automations.yaml
automation folder: !include_dir_list ../automations

script: !include ../scripts.yaml

python_script:

mobile_app:
# alexa:
#   smart_home:
#     locale: it-IT
#     endpoint: https://api.eu.amazonalexa.com/v3/events
#     client_id: !secret alexa_client_id
#     client_secret: !secret alexa_client_secret
