---
id: "notify_armed_home"
alias: "Send notification when alarm is Armed in Home mode"
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: "armed_home"
action:
  - service: telegram_bot.send_message
    data:
      target:
        - "-212768319"
      title: "ALLARME attivato 🦾"
      message: "L'allarme è stato attivato in modalità **Home**"
