---
id: "notify_alarm_disarm"
alias: "Send notification when alarm is Disarmed"
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: "disarmed"
action:
  - service: telegram_bot.send_message
    data:
      entity_id:
        - "notify.telegram_bot_344202687_212768319"
      title: "ALARM disarmed 🗝"
      message: "The alarm is Disarmed"
