homeassistant:
  # Name of the location where Home Assistant is running
  name: Catingham Palace
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  
  customize:
    switch.driveway_lights:
      icon: mdi:lightbulb
    switch.driveway_gate:
      icon: mdi:gate
    switch.driveway_door:
      icon: mdi:lock
    switch.stair_front_door:
      icon: mdi:stairs
    sensor.entryway_thermostat_humidity:
      icon: mdi:water-percent
    sensor.entryway_thermostat_hvac_state:
      hidden: true
    binary_sensor.entryway_thermostat_fan:
      hidden: true
    binary_sensor.entryway_thermostat_has_leaf:
      hidden: true
    binary_sensor.entryway_thermostat_is_locked:
      hidden: true
    binary_sensor.entryway_thermostat_is_using_emergency_heat:
      hidden: true
    binary_sensor.entryway_thermostat_online:
      hidden: true
    binary_sensor.living_room_camera_online:
      hidden: true
    sensor.entryway_thermostat_target:
      hidden: true
    sensor.entryway_thermostat_operation_mode:
      hidden: true
    climate.entryway:
      friendly_name: Nest
    binary_sensor.rubens_bed:
      icon: mdi:hotel
    binary_sensor.valentina_bed:
      icon: mdi:hotel
     
    sensor.greenhouse_temperature:
      icon: mdi:thermometer
      friendly_name: "Temperature"
    sensor.greenhouse_humidity:
      icon: mdi:water-percent
      friendly_name: "Humidity"
    sensor.greenhouse_plant1_soil_moisture:
      icon: mdi:cup-water
      friendly_name: "Soil moisture"
    fan.greenhouse_ventilation:
      friendly_name: "Ventilation"
    light.greenhouse_light:
      friendly_name: "Light"

    binary_sensor.living_room_camera_person_detected:
      icon: mdi:walk
    binary_sensor.living_room_camera_motion_detected:
      icon: mdi:cat
    binary_sensor.living_room_camera_sound_detected:
      icon: mdi:bullhorn

    automation.leave_cat_passage_living_room:
      friendly_name: Leave cat passage
      icon: mdi:cat
    automation.leave_cat_passage_green_room:
      friendly_name: Leave cat passage
      icon: mdi:cat
    automation.leave_cat_passage_bedroom:
      friendly_name: Leave cat passage
      icon: mdi:cat
    automation.leave_cat_passage_kitchen:
      friendly_name: Leave cat passage
      icon: mdi:cat
      
    automation.all_roller_shutter_down:
      friendly_name: All the way down
      icon: mdi:arrow-down-bold
    automation.all_roller_shutter_up:
      icon: mdi:arrow-up-bold
      friendly_name: All the way up
    automation.roller_shutter_sunrise:
      friendly_name: Roller shutter up at sunrise
      icon: mdi:weather-sunset-up
    automation.roller_shutter_sunset:
      friendly_name: Roller shutter down at sunset
      icon: mdi:weather-sunset-down


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  # Weather Prediction
  - platform: yr
  - platform: mqtt
    state_topic: "catingham_palace/simon_says/game"
    name: "Simon Says"
    qos: 1
  - platform: mqtt
    state_topic: "catingham_palace/greenhouse/temperature"
    name: "Greenhouse temperature"
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "catingham_palace/greenhouse/humidity"
    name: "Greenhouse humidity"
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "catingham_palace/greenhouse/plant1/soil_moisture"
    name: "Greenhouse plant1 soil_moisture"
    unit_of_measurement: '%'

# Text to speech
tts:
  platform: google




mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: lamp1
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

switch:
  - platform: mqtt
    name: "Driveway Gate"
    command_topic: "catingham_palace/driveway/gate/state"
    state_topic: "catingham_palace/driveway/gate/state"
    payload_on: "OPEN"
    payload_off: "CLOSED"
    qos: 1
  - platform: mqtt
    name: "Driveway Door"
    command_topic: "catingham_palace/driveway/door/state"
    state_topic: "catingham_palace/driveway/door/state"
    payload_on: "OPEN"
    payload_off: "CLOSED"
    qos: 1
  - platform: mqtt
    name: "Stair Front door"
    command_topic: "catingham_palace/stair/front_door/state"
    state_topic: "catingham_palace/stair/front_door/state"
    payload_on: "OPEN"
    payload_off: "CLOSED"
    qos: 1
  - platform: mqtt
    name: "Driveway Lights"
    command_topic: "catingham_palace/driveway/lights/state"
    state_topic: "catingham_palace/driveway/lights/state"
    qos: 1
 
device_tracker:
  - platform: owntracks

#  - platform: nmap_tracker
#    hosts: 192.168.0.1/24
#    home_interval: 300
#    track_new_devices: false
#  - platform: owntracks
   
light:
  - platform: mqtt
    name: "Greenhouse light"
    qos: 1
    optimistic: false
    retain: true
    command_topic: "catingham_palace/greenhouse/light/switch"
    state_topic: "catingham_palace/greenhouse/light/status"
fan:
  - platform: mqtt
    name: "Greenhouse ventilation"
    qos: 1
    optimistic: false
    retain: true
    command_topic: "catingham_palace/greenhouse/ventilation/switch"
    state_topic: "catingham_palace/greenhouse/ventilation/status"

ifttt:
  key: !secret ifttt_key

notify:
  - name: CatinghamPalaceBot
    platform: telegram
    #chat_id: !secret telegram_rubens_chat
    chat_id: !secret telegram_catingham_palace_group
  - name: telegram2rubens
    platform: telegram
    chat_id: !secret telegram_rubens_chat
  - name: telegram2vale
    platform: telegram
    chat_id: !secret telegram_vale_chat

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_rubens_chat
      - !secret telegram_vale_chat
      - !secret telegram_catingham_palace_group

input_number:
  green_room_rolling_shutter:
    name: Green room rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  living_room_left_rolling_shutter:
    name: Living room left rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  living_room_right_rolling_shutter:
    name: Living room right rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  kitchen_left_rolling_shutter:
    name: Kitchen left rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  kitchen_right_rolling_shutter:
    name: Kitchen right rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  pink_room_rolling_shutter:
    name: Pink room rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  bedroom_rolling_shutter:
    name: Bedroom rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  bathroom_rolling_shutter:
    name: Bathroom rolling shutter
    min: 0
    max: 100
    initial: 100
    step: 5
    unit_of_measurement: step  
    icon: mdi:blinds
  cat_passage:
    name: Cat passage
    min: 0
    max: 100
    initial: 25
    step: 5
    unit_of_measurement: step  
    icon: mdi:cat
    
input_boolean:
  avoid_bedroom_roller_shutter_up_during_weekend:
    name: "Avoid bedroom roller shutter up during weekend"
    initial: on
    icon: mdi:sleep

binary_sensor:
  - platform: mqtt
    state_topic: "catingham_palace/bedroom/bed/rubens"
    name: "Rubens bed"
    qos: 1
    payload_on: "IN"
    payload_off: "OUT"
    device_class: "occupancy"
  - platform: mqtt
    state_topic: "catingham_palace/bedroom/bed/valentina"
    name: "Valentina bed"
    qos: 1
    payload_on: "IN"
    payload_off: "OUT"
    device_class: "occupancy"
  - platform: mqtt
    state_topic: "catingham_palace/green_room/motion"
    name: "Green room motion"
    qos: 1
    device_class: "motion"
  - platform: mqtt
    state_topic: "catingham_palace/living_room/right_window/state"
    name: "Living room right window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/living_room/left_window/state"
    name: "Living room left window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/kitchen/left_window/state"
    name: "Kitchen left window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/kitchen/right_window/state"
    name: "Kitchen right window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/green_room/window/state"
    name: "Green room window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/pink_room/window/state"
    name: "Pink room window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/bedroom/window/state"
    name: "Bedroom window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"
  - platform: mqtt
    state_topic: "catingham_palace/bathroom/window/state"
    name: "Bathroom window"
    qos: 1
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: "opening"

camera:
  - platform: mjpeg
    mjpeg_url: http://localhost:8081
    name: Green room camera

cover:
  - platform: template
    covers:
      all_roller_shutters:
        friendly_name: "All roller shutters"
        close_cover:
          service: automation.turn_on
          entity_id: automation.all_roller_shutter_down
        open_cover:
          service: automation.turn_on
          entity_id: automation.all_roller_shutter_up


group: !include groups.yaml
automation: !include automations.yaml
zone: !include zones.yaml
