homeassistant:
  # Name of the location where Home Assistant is running
  name: Catingham Palace
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome

  customize: !include customize.yaml

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 15

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: info
  logs:
    roomba: warning
    homeassistant.components.vacuum: warning

# Track the sun
sun:

sensor:
  # Weather Prediction
  - platform: yr
  - platform: mqtt
    state_topic: "catingham_palace/simon_says/game"
    name: "Simon Says"
    qos: 1
  - platform: mqtt
    state_topic: "catingham_palace/greenhouse/temperature"
    name: "Greenhouse temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "catingham_palace/greenhouse/humidity"
    name: "Greenhouse humidity"
    unit_of_measurement: "%"
    value_template: "{{ value | round }}"
  - platform: mqtt
    state_topic: "catingham_palace/greenhouse/plant1/soil_moisture"
    name: "Greenhouse plant1 soil_moisture"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "catingham_palace/entryway/temperature"
    name: "Entryway temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "catingham_palace/entryway/humidity"
    name: "Entryway humidity"
    unit_of_measurement: "%"
    value_template: "{{ value | round }}"
  - platform: mqtt
    state_topic: "catingham_palace/emonpi/power1"
    name: "EmonPi Power 1"
    unit_of_measurement: "W"
  - platform: mqtt
    state_topic: "catingham_palace/emonpi/power2"
    name: "EmonPi Power 2"
    unit_of_measurement: "W"
  - platform: mqtt
    state_topic: "catingham_palace/emonpi/power1pluspower2"
    name: "EmonPi Total power"
    unit_of_measurement: "W"
  - platform: mqtt
    state_topic: "catingham_palace/emonpi/total_power_kwh"
    name: "EmonPi Total power kWh"
    value_template: "{{ value | round(2) }}"
    unit_of_measurement: "kWh"

  - platform: mqtt
    state_topic: "catingham_palace/mqtt_cover_test"
    name: "mqtt_cover_test"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "catingham_palace/green_room/rolling_shutter/position"
    name: "cover_position_green_room"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "catingham_palace/green_room/air_quality_meter"
    name: "air_quality_meter"
    value_template: "{{ value_json }}"
    #availability_topic: "catingham_palace/green_room/air_quality_meter/availability"
    json_attributes_topic: "catingham_palace/green_room/air_quality_meter"

  - platform: template
    sensors:
      air_quality_pm10:
        friendly_name: PM1.0
        value_template: "{{ states.sensor.air_quality_meter.attributes.pm10 }}"
        unit_of_measurement: "μg/m3"
      air_quality_pm25:
        friendly_name: PM2.5
        value_template: "{{ states.sensor.air_quality_meter.attributes.pm25 }}"
        unit_of_measurement: "μg/m3"
      air_quality_pm100:
        friendly_name: PM10
        value_template: "{{ states.sensor.air_quality_meter.attributes.pm100 }}"
        unit_of_measurement: "μg/m3"
      air_quality_pm10_env:
        friendly_name: PM1.0 (atmospheric environment)
        value_template: "{{ states.sensor.air_quality_meter.attributes.pe10 }}"
        unit_of_measurement: "μg/m3"
      air_quality_pm25_env:
        friendly_name: PM2.5 (atmospheric environment)
        value_template: "{{ states.sensor.air_quality_meter.attributes.pe25 }}"
        unit_of_measurement: "μg/m3"
      air_quality_pm100_env:
        friendly_name: PM10 (atmospheric environment)
        value_template: "{{ states.sensor.air_quality_meter.attributes.pe100 }}"
        unit_of_measurement: "μg/m3"

      air_quality_pt03:
        friendly_name: Particles > 0.3um / 0.1L air
        value_template: "{{ states.sensor.air_quality_meter.attributes.pt03 }}"
      air_quality_pt05:
        friendly_name: Particles > 0.5um / 0.1L air
        value_template: "{{ states.sensor.air_quality_meter.attributes.pt05 }}"
      air_quality_pt10:
        friendly_name: Particles > 1.0um / 0.1L air
        value_template: "{{ states.sensor.air_quality_meter.attributes.pt10 }}"
      air_quality_pt25:
        friendly_name: Particles > 2.5um / 0.1L air
        value_template: "{{ states.sensor.air_quality_meter.attributes.pt25 }}"
      air_quality_pt50:
        friendly_name: Particles > 5.0um / 0.1L air
        value_template: "{{ states.sensor.air_quality_meter.attributes.pt50 }}"
      air_quality_pt100:
        friendly_name: Particles > 10.0um / 0.1L air
        value_template: "{{ states.sensor.air_quality_meter.attributes.pt100 }}"

      air_quality_temperature:
        friendly_name: Temperature
        value_template: "{{ states.sensor.air_quality_meter.attributes.tem }}"
        unit_of_measurement: "°C"
      air_quality_humidity:
        friendly_name: Humidity
        value_template: "{{ states.sensor.air_quality_meter.attributes.hum }}"
        unit_of_measurement: "%"
      air_quality_formaldehyde:
        friendly_name: Formaldehyde
        value_template: "{{ states.sensor.air_quality_meter.attributes.hcho }}"
        unit_of_measurement: "mg/m3"

# Text to speech
tts:
  platform: google_translate

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: lamp1
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

lock:
  - platform: mqtt
    name: "Driveway Gate"
    command_topic: "catingham_palace/driveway/gate/state"
    state_topic: "catingham_palace/driveway/gate/state"
    payload_unlock: "OPEN"
    payload_lock: "CLOSED"
    optimistic: false
    qos: 1
  - platform: mqtt
    name: "Driveway Door"
    command_topic: "catingham_palace/driveway/door/state"
    state_topic: "catingham_palace/driveway/door/state"
    payload_unlock: "OPEN"
    payload_lock: "CLOSED"
    optimistic: false
    qos: 1
  - platform: mqtt
    name: "Stair Front door"
    command_topic: "catingham_palace/stair/front_door/state"
    state_topic: "catingham_palace/stair/front_door/state"
    payload_unlock: "OPEN"
    payload_lock: "CLOSED"
    optimistic: false
    qos: 1

switch:
  - platform: mqtt
    name: "Automatic cat passage"
    command_topic: "catingham_palace/roller_shutters/automatic_cat_passage"
    state_topic: "catingham_palace/roller_shutters/automatic_cat_passage"
    optimistic: false
    retain: true
    qos: 1

  - platform: mqtt
    name: "Greenhouse humidifier power"
    command_topic: "catingham_palace/greenhouse/humidifier/switch"
    state_topic: "catingham_palace/greenhouse/humidifier/status"
    optimistic: false
    retain: true
    qos: 1
  - platform: mqtt
    name: "Greenhouse humidifier status leds"
    command_topic: "catingham_palace/greenhouse/humidifier/leds/switch"
    state_topic: "catingham_palace/greenhouse/humidifier/leds/status"
    optimistic: false
    retain: true
    qos: 1
  - platform: mqtt
    name: "Greenhouse humidifier mode"
    command_topic: "catingham_palace/greenhouse/humidifier/mode"
    state_topic: "catingham_palace/greenhouse/humidifier/mode"
    payload_off: "manual"
    payload_on: "auto"
    optimistic: false
    retain: true
    qos: 1
  - platform: mqtt
    name: "Roller shutters away mode"
    command_topic: "catingham_palace/roller_shutters/away_mode"
    state_topic: "catingham_palace/roller_shutters/away_mode"
    optimistic: false
    retain: true
    qos: 1
  - platform: mqtt
    name: "Pallone"
    state_topic: "catingham_palace/green_room/pallone/stat/POWER"
    command_topic: "catingham_palace/green_room/pallone/cmnd/POWER"
    availability_topic: "catingham_palace/green_room/pallone/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

owntracks:
  # max_gps_accuracy: 200

# device_tracker:
#   - platform: owntracks

#  - platform: nmap_tracker
#    hosts: 192.168.0.1/24
#    home_interval: 300
#    track_new_devices: false
#  - platform: owntracks

light:
  - platform: mqtt
    name: "Greenhouse"
    qos: 1
    optimistic: false
    retain: true
    command_topic: "catingham_palace/greenhouse/light/switch"
    state_topic: "catingham_palace/greenhouse/light/status"
  - platform: mqtt
    name: "Driveway"
    command_topic: "catingham_palace/driveway/lights/state"
    state_topic: "catingham_palace/driveway/lights/state"
    qos: 1
  - platform: mqtt
    name: "Entryway"
    state_topic: "catingham_palace/entryway/light/stat/POWER"
    command_topic: "catingham_palace/entryway/light/cmnd/POWER"
    availability_topic: "catingham_palace/entryway/light/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Kitchen countertop"
    state_topic: "catingham_palace/kitchen/countertop_light/stat/POWER"
    command_topic: "catingham_palace/kitchen/countertop_light/cmnd/POWER"
    availability_topic: "catingham_palace/kitchen/countertop_light/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
  - platform: mqtt
    name: "Kitchen hood"
    state_topic: "catingham_palace/kitchen/hood_light/stat/POWER"
    command_topic: "catingham_palace/kitchen/hood_light/cmnd/POWER"
    availability_topic: "catingham_palace/kitchen/hood_light/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "Living room main"
    state_topic: "catingham_palace/living_room/light/stat/RESULT"
    value_template: "{{ value_json.POWER3 }}"
    command_topic: "catingham_palace/living_room/light/cmnd/POWER3"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "catingham_palace/living_room/light/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
  - platform: mqtt
    name: "Kitchen main"
    state_topic: "catingham_palace/living_room/light/stat/RESULT"
    value_template: "{{ value_json.POWER1 }}"
    command_topic: "catingham_palace/living_room/light/cmnd/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "catingham_palace/living_room/light/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
  - platform: mqtt
    name: "Green room desktop light"
    state_topic: "catingham_palace/green_room/desktop_light/stat/POWER"
    command_topic: "catingham_palace/green_room/desktop_light/cmnd/POWER"
    availability_topic: "catingham_palace/green_room/desktop_light/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

fan:
  - platform: mqtt
    name: "Greenhouse ventilation"
    qos: 1
    optimistic: false
    retain: true
    command_topic: "catingham_palace/greenhouse/ventilation/switch"
    state_topic: "catingham_palace/greenhouse/ventilation/status"

ifttt:
  key: !secret ifttt_key

notify:
  - name: CatinghamPalaceBot
    platform: telegram
    #chat_id: !secret telegram_rubens_chat
    chat_id: !secret telegram_catingham_palace_group
  - name: telegram2rubens
    platform: telegram
    chat_id: !secret telegram_rubens_chat
  - name: telegram2vale
    platform: telegram
    chat_id: !secret telegram_vale_chat

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_rubens_chat
      - !secret telegram_vale_chat
      - !secret telegram_catingham_palace_group

input_number:
  covers_min_position:
    name: Covers min position
    min: 0
    max: 100
    initial: 25
    step: 5
    unit_of_measurement: "%"
    icon: mdi:cat
  greenhouse_humidifier_target_humidity:
    name: Target humidity
    min: 0
    max: 100
    step: 5
    initial: 60
    unit_of_measurement: "%"
    icon: mdi:water-percent

binary_sensor: !include_dir_merge_list binary_sensor/

camera: !include camera.yaml

cover: !include covers.yaml

person:
  - name: Rubens
    id: rubens
    device_trackers:
      - device_tracker.rubens_phone
  - name: Valentina
    id: valentina
    device_trackers:
      - device_tracker.valentina_phone

history_graph:
  greenhouse_temperature:
    name: "Temperature"
    refresh: 60
    entities:
      - sensor.greenhouse_temperature
  greenhouse_humidity:
    name: "Humidity"
    refresh: 60
    entities:
      - sensor.greenhouse_humidity
  greenhouse_plant1_soil_moisture:
    name: "Soil moisture"
    refresh: 60
    entities:
      - sensor.greenhouse_plant1_soil_moisture
  emonpi_power:
    name: "Power consumption"
    refresh: 5
    entities:
      - sensor.emonpi_total_power
      - sensor.emonpi_power_1
      - sensor.emonpi_power_2
  emonpi_power_kwh:
    name: "Power consumption kWh"
    refresh: 60
    entities:
      - sensor.emonpi_total_power_kwh

media_player:
  - platform: samsungtv
    name: Living room TV
    host: !secret living_room_tv_ip
    mac: !secret living_room_tv_mac_address
    port: 8001

input_select:
  roller_shutters_scene:
    name: Roller shutters scene
    options:
      - "day"
      - "night"

google_assistant:
  project_id: catingham-palace
  service_account: !secret google_assistant_service_account
  entity_config:
    lock.driveway_gate:
      aliases:
        - cancello
        - cancellone
      room: Driveway
    lock.driveway_door:
      aliases:
        - cancelletto
      room: Driveway
    lock.stair_front_door:
      aliases:
        - porta
      room: Scale
    light.driveway_lights:
      aliases:
        - luci in giardino
        - luci nel vialetto
      room: Driveway
    light.entryway:
      room: Ingresso
    light.living_room_main:
      room: Sala
      name: Luce grande
      aliases:
        - luce principale
    light.kitchen_main:
      room: Cucina
      name: Luce grande
      aliases:
        - luce principale
    light.kitchen_hood:
      room: Cucina
      name: Luce della cappa
    light.kitchen_countertop:
      room: Cucina
      name: Luce piano cucina
      aliases:
        - luce sotto lavello
    light.green_room_desktop_light:
      room: Ufficio
      name: Luce scrivania

cast:

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  name: S200
  bed: true
  number_of_tools: 1

timer:
  tv_shut_down_delay:
    duration: 30

vacuum:
  - platform: roomba
    name: Roomba
    host: !secret roomba_ip_address
    username: !secret roomba_username
    password: !secret roomba_password

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: home

lovelace:
  mode: yaml

system_health:

group: !include groups.yaml
automation: !include automations.yaml
automation folder: !include_dir_list automations
zone: !include zones.yaml

script: !include scripts.yaml

python_script:

mobile_app:
# alexa:
#   smart_home:
#     locale: it-IT
#     endpoint: https://api.eu.amazonalexa.com/v3/events
#     client_id: !secret alexa_client_id
#     client_secret: !secret alexa_client_secret
