---
homeassistant:
  name: Catingham Palace

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  external_url: !secret http_base_url
  time_zone: Europe/Rome
  unit_system: metric
  country: "IT"

  customize: !include_dir_merge_named ./customizations/entities
  customize_domain: !include_dir_merge_named ./customizations/domains
  customize_glob: !include_dir_merge_named ./customizations/globs

  packages: !include_dir_named ./integrations
