---
homeassistant:
  name: Catingham Palace

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Rome

  customize: !include_dir_merge_named ./customizations/entities
  customize_domain: !include_dir_merge_named ./customizations/domains
  customize_glob: !include_dir_merge_named ./customizations/globs

  packages: !include_dir_named ./integrations
