- platform: rollershutteriot
  name: "Green room"
  command_topic: "catingham_palace/green_room/rolling_shutter/position/set"
  position_topic: "catingham_palace/green_room/rolling_shutter/position"
  set_position_topic: "catingham_palace/green_room/rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100
  position_min: input_number.covers_min_position
  position_min_enable: switch.automatic_cat_passage
  window_sensor: binary_sensor.green_room_window

- platform: rollershutteriot
  name: "Pink room"
  command_topic: "catingham_palace/pink_room/rolling_shutter/position/set"
  position_topic: "catingham_palace/pink_room/rolling_shutter/position"
  set_position_topic: "catingham_palace/pink_room/rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100

- platform: rollershutteriot
  name: "Kitchen left"
  command_topic: "catingham_palace/kitchen/left_rolling_shutter/position/set"
  position_topic: "catingham_palace/kitchen/left_rolling_shutter/position"
  set_position_topic: "catingham_palace/kitchen/left_rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100
  position_min: input_number.covers_min_position
  position_min_enable: switch.automatic_cat_passage
  window_sensor: binary_sensor.kitchen_left_window

- platform: rollershutteriot
  name: "Kitchen right"
  command_topic: "catingham_palace/kitchen/right_rolling_shutter/position"
  position_topic: "catingham_palace/kitchen/right_rolling_shutter/position"
  set_position_topic: "catingham_palace/kitchen/right_rolling_shutter/position"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100
  position_min: input_number.covers_min_position
  position_min_enable: switch.automatic_cat_passage
  window_sensor: binary_sensor.kitchen_right_window

- platform: rollershutteriot
  name: "Living room left"
  command_topic: "catingham_palace/living_room/left_rolling_shutter/position/set"
  position_topic: "catingham_palace/living_room/left_rolling_shutter/position"
  set_position_topic: "catingham_palace/living_room/left_rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100

- platform: rollershutteriot
  name: "Living room right"
  command_topic: "catingham_palace/living_room/right_rolling_shutter/position/set"
  position_topic: "catingham_palace/living_room/right_rolling_shutter/position"
  set_position_topic: "catingham_palace/living_room/right_rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100
  position_min: input_number.covers_min_position
  position_min_enable: switch.automatic_cat_passage
  window_sensor: binary_sensor.living_room_right_window

- platform: rollershutteriot
  name: "Bathroom"
  command_topic: "catingham_palace/bathroom/rolling_shutter/position/set"
  position_topic: "catingham_palace/bathroom/rolling_shutter/position"
  set_position_topic: "catingham_palace/bathroom/rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100

- platform: rollershutteriot
  name: "Bedroom"
  command_topic: "catingham_palace/bedroom/rolling_shutter/position/set"
  position_topic: "catingham_palace/bedroom/rolling_shutter/position"
  set_position_topic: "catingham_palace/bedroom/rolling_shutter/position/set"
  qos: 1
  retain: false
  optimistic: true
  payload_close: 0
  payload_open: 100
  position_min: input_number.covers_min_position
  position_min_enable: switch.automatic_cat_passage
  window_sensor: binary_sensor.bedroom_room_window

- platform: template
  covers:
    all_roller_shutters:
      friendly_name: "All roller shutters"
      close_cover:
        service: automation.turn_on
        entity_id: automation.all_roller_shutter_down
      open_cover:
        service: automation.turn_on
        entity_id: automation.all_roller_shutter_up