title: Home
views:
  - title: default_view
    id: home
    icon: mdi:home
    cards:
      - type: entities
        title: Family locations
        show_header_toggle: false
        entities:
          - device_tracker.rubens_phone
          - device_tracker.valentina_phone
      - type: weather-forecast
        entity: weather.home
      - type: entities
        title: Environment
        show_header_toggle: true
        entities:
          - sun.sun
          - climate.entryway
          - cover.test_cover
      - type: glance
        title: Driveway
        show_header_toggle: true
        show_state: false
        entities:
          - entity: lock.driveway_gate
            name: Gate
            tap_action: toggle
          - entity: lock.driveway_door
            name: Door
            tap_action: toggle
          - entity: lock.stair_front_door
            name: Stair
            tap_action: toggle
          - entity: light.driveway_lights
            name: Lights
            tap_action: toggle
      - type: entities
        title: Kitchen
        show_header_toggle: true
        entities:
          - climate.entryway
          - sensor.entryway_thermostat_temperature
          - sensor.entryway_thermostat_humidity
      
      - type: picture-glance
        title: Living room
        camera_image: camera.living_room
        tap_action: dialog
        entities:
          - camera.living_room
          - binary_sensor.living_room_camera_person_detected
          - binary_sensor.living_room_camera_motion_detected
          - binary_sensor.living_room_camera_sound_detected   
        
      - type: media-control
        entity: media_player.living_room_tv
      - type: entities
        title: Green Room
        show_header_toggle: true
        entities:
          - binary_sensor.green_room_motion
      - type: glance
        title: Entryway
        show_header_toggle: false
        show_name: false
        entities:
          - sensor.entryway_temperature
          - sensor.entryway_humidity
          - binary_sensor.entryway_motion
          - entity: light.entryway
            tap_action: toggle
          
  - title: Roller Shutters
    id: roller-shutters
    icon: mdi:blinds
    cards:
      - type: entities
        title: Global
        show_header_toggle: true
        entities:
          - automation.all_roller_shutter_up
          - automation.all_roller_shutter_down
          - cover.all_roller_shutters
      - type: entities
        title: Kitchen
        show_header_toggle: true
        entities:
          - input_number.kitchen_left_rolling_shutter
          - input_number.kitchen_right_rolling_shutter
          - input_boolean.cat_passage_kitchen
          - binary_sensor.kitchen_left_window
          - binary_sensor.kitchen_right_window
      - type: entities
        title: Living Room
        show_header_toggle: true
        entities:
          - input_number.living_room_left_rolling_shutter
          - input_number.living_room_right_rolling_shutter
          - input_boolean.cat_passage_living_room
          - binary_sensor.living_room_left_window
          - binary_sensor.living_room_right_window
      - type: entities
        title: Bedroom
        show_header_toggle: true
        entities:
          - input_number.bedroom_rolling_shutter
          - input_boolean.cat_passage_bedroom
          - binary_sensor.bedroom_window
      - type: entities
        title: Green Room
        show_header_toggle: true
        entities:
          - cover.green_room
          - input_boolean.cat_passage_green_room
          - binary_sensor.green_room_window
      - type: entities
        title: Pink Room
        show_header_toggle: true
        entities:
          - input_number.pink_room_rolling_shutter
          - binary_sensor.pink_room_window
      - type: entities
        title: Bathroom
        show_header_toggle: true
        entities:
          - input_number.bathroom_rolling_shutter
          - binary_sensor.bathroom_window
      - type: entities
        title: Config
        show_header_toggle: true
        entities:
          - automation.roller_shutter_sunrise
          - automation.roller_shutter_sunset
          - input_boolean.avoid_bedroom_roller_shutter_up_during_weekend
          - switch.automatic_cat_passage
          - input_number.cat_passage
          
  - title: Greenhouse
    id: greenhouse
    icon: mdi:leaf
    cards:
      - type: entities
        title: Environment
        show_header_toggle: true
        entities:
          - sensor.greenhouse_temperature
          - sensor.greenhouse_humidity
          - sensor.greenhouse_plant1_soil_moisture
          - light.greenhouse_light
          - fan.greenhouse_ventilation
      - type: entities
        title: Humidifier
        show_header_toggle: true
        entities:
          - input_number.greenhouse_humidifier_target_humidity
          - switch.greenhouse_humidifier_mode
          - switch.greenhouse_humidifier_power
          - switch.greenhouse_humidifier_status_leds
      - type: history-graph
        title: Temperature
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.greenhouse_temperature
      - type: history-graph
        title: Humidity
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.greenhouse_humidity
      - type: history-graph
        title: Soil moisture
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.greenhouse_plant1_soil_moisture
          
  - title: energy
    id: energy
    icon: mdi:flash
    cards:
      - type: entities
        title: Energy consumption
        show_header_toggle: true
        entities:
          - sensor.emonpi_total_power
          - sensor.emonpi_power_1
          - sensor.emonpi_power_2
          - sensor.emonpi_total_power_kwh
      - type: history-graph
        title: Power consumption
        hours_to_show: 24
        refresh_interval: 5
        entities:
          - sensor.emonpi_total_power
          - sensor.emonpi_power_1
          - sensor.emonpi_power_2
      - type: history-graph
        title: Power consumption kWh
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.emonpi_total_power_kwh

  - title: people
    id: people
    icon: mdi:account-multiple
    cards:          
    - type: entities
      title: Family locations
      show_header_toggle: true
      entities:
        - device_tracker.rubens_phone
        - device_tracker.valentina_phone
    - type: map
      entities:
        - device_tracker.rubens_phone
        - device_tracker.valentina_phone
                  
  - title: Air quality
    id: air-quality
    icon: mdi:speedometer
    cards:
    - type: glance
      title: Concentration Units (standard)
      show_header_toggle: false
      entities:
        - sensor.air_quality_pm10
        - sensor.air_quality_pm25
        - sensor.air_quality_pm100
    - type: glance
      title: Concentration Units (environmental)
      show_header_toggle: false
      entities:
        - name: PM1.0
          entity: sensor.air_quality_pm10_env
        - name: PM2.5
          entity: sensor.air_quality_pm25_env
        - name: PM10
          entity: sensor.air_quality_pm100_env
    - type: glance
      title: Number of particles
      show_header_toggle: false
      columns: 6
      entities:
        - name: "> 0.3μg"
          entity: sensor.air_quality_pt03
        - name: "> 0.5μg"
          entity: sensor.air_quality_pt05
        - name: "> 1.0μg"
          entity: sensor.air_quality_pt10 
        - name: "> 2.5μg"
          entity: sensor.air_quality_pt25
        - name: "> 5.0μg"
          entity: sensor.air_quality_pt50 
        - name: "> 10.0μg"
          entity: sensor.air_quality_pt100           
        
    - type: entities
      title: Others
      show_header_toggle: false
      entities:
        - sensor.air_quality_formaldehyde
        - sensor.air_quality_temperature
        - entity: sensor.air_quality_humidity
          icon: mdi:water-percent
     
    - type: history-graph
      title: 'Concentration Units (standard)'
      entities:
        - sensor.air_quality_pm10
        - sensor.air_quality_pm25
        - sensor.air_quality_pm100  
        
    - type: history-graph
      title: 'Concentration Units (environmental)'
      entities:
        - sensor.air_quality_pm10
        - sensor.air_quality_pm25
        - sensor.air_quality_pm100  