---
id: "living_room_roller_shutter_up_delayed"
alias: "Living room roller shutter up delayed"
initial_state: True
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.tv_shutdown_delay
action:
  - service: cover.open_cover
    entity_id: cover.living_room_left
