---
id: "roller_shutter_sunset"
alias: "Roller shutter sunset"
description: "Close all covers at sunset"
initial_state: False
trigger:
  platform: sun
  event: sunset
#    offset: "00:30:00"
action:
  service: python_script.cover_sunset
  entity_id: all
