---
id: "roller_shutter_away_mode"
alias: "Roller shutter away mode"
description: "Switch cover mode to away when nobody is in the house"
initial_state: True
trigger:
  platform: state
  entity_id: group.family
  from: "home"
  to: "not_home"
action:
  - service: python_script.cover_mode
    data_template:
      mode: "fuori casa"
  - service: notify.catinghampalacebot
    data_template:
      message: "Siate usciti tutti di casa 🏡A presto! 🐈"
