---
id: "ECAA0EA1-1B95-4473-A245-FB309E025CA0"
alias: "energy_power_alert"
description: "Notifies power compsuntion over threshold"
initial_state: True
trigger:
  platform: numeric_state
  entity_id: sensor.total_power
  value_template: "{{ (state.state | float) - (states('input_number.power_alert_threshold') | float) }}"
  above: 0
  for: "00:00:10"
action:
  - condition: template
    value_template: '{{ (4500 * 0.9) < (states("sensor.total_power")|float) }}'
  - service: notify.catinghampalacebot
    data_template:
      message: |-
        🐙 **Consumo elettrico**: {{ states('sensor.total_power') | int }} W
        🐈 {{ states('sensor.power1') | int }} W | 👵🏻 {{ states('sensor.power2') | int }} W
        {{ [
          'Cudiaul! Schepa giò che se no chi le sciopa su tuch coss',
          'Smorza giò, crist!',
          'Va che te fa salta giù la curent',
          'Te paghei te i bulett?'
          'Té! Va che la custa la curent!'
        ] | random }}
  - service: notify.alexa_media
    data_template:
      data:
        type: tts
        method: speak
      message: |-
        Attenzione! State consumando {{states('sensor.total_power')|int}} watt, rischia di saltare la luce! 
        {% if states('sensor.power2')|int / 4500 > 0.25 %}
          Giù da basso hanno acceso qualcosa di grosso da {{states('sensor.power2')|int}} Watt.
        {% endif %}
      target:
        - media_player.laboratorio
        - media_player.cucina
