---
id: "B355A5D0-FECC-4DB6-BA13-EF05D41566DE"
alias: "energy_tariff_offpeak"
description: "Set energy utility meters offpeak tariff"
initial_state: True
trigger:
  - platform: time
    at: "19:00:00"
action:
  - service: select.select_option
    target:
      entity_id:
        - select.total_energy_daily
        - select.total_energy_monthly
    data:
      option: offpeak
