---
alias: "Vacuum start when away"
description: "Starts vacuuming process when nobody's home"
trigger:
  platform: state
  entity_id: group.family
  from: "home"
  to: "not_home"
condition:
  - condition: state
    entity_id: vacuum.roomba
    state: "docked"
    for:
      hours: 12 # if didn't clean up in the last 12 hours
action:
  - service: vacuum.start
    entity_id: vacuum.roomba
  - service: telegram_bot.send_message
    data:
      target:
        - "-212768319"
      message: |-
        Già che ci sono pulisco il pavimento! 🤖🧹
      inline_keyboard:
        - "No grazie, ferma"
        - "/stop_vacuum"
