---
alias: "Vacuum stop callback"
description: "Stops vacuuming process on Telegram callback"
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    command: "/stop_vacuum"
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: "{{ trigger.event.data.id }}"
      message: "Ok, fermo subito!"
      show_alert: true
  - service: vacuum.stop
    entity_id: vacuum.roomba
  # - service: telegram_bot.edit_replymarkup
  #   data_template:
  #     message_id: "{{ trigger.event.data.message.message_id }}"
  #     chat_id: "{{ trigger.event.data.chat_id }}"
  #     data:
  #       inline_keyboard: [[]]
  - service: telegram_bot.send_message
    data_template:
      target: "{{ trigger.event.data.chat_id }}"
      message: "Ok {{ trigger.event.data.from_first | capitalize }}, ho fermato 😊"
