---
id: "driveway_lights_on_valentina_left_work"
alias: "Driveway lights ON when Valentina left work"
initial_state: True
mode: restart
trigger:
  - platform: zone
    entity_id: person.valentina
    zone: zone.work
    event: leave
condition:
  # during the night
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: sun
        before: sunrise
action:
  - service: light.toggle
    entity_id: light.driveway
  - delay:
      minutes: 10
  - service: light.toggle
    entity_id: light.driveway
  - service: notify.telegram2rubens
    data:
      message: "Ho spento le luci nel vialetto 💡🚗"
