---
id: "valentina_left_work_lights_on"
alias: "Valentina left work - lights on"
initial_state: True
mode: restart
trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.valentina_left_work
condition:
  # during the night
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: sun
        before: sunrise
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.kitchen_countertop
        - light.entryway
  - service: light.toggle
    target:
      entity_id: light.driveway
