---
id: "valentina_left_work"
alias: "Valentina left work"
initial_state: True
trigger:
  - platform: zone
    entity_id: person.valentina
    zone: zone.work
    event: leave
condition:
  # let Valentina arrive at work (enter exit zone multiple times)
  condition: not
  conditions:
    - condition: state
      entity_id: person.valentina
      state: home
      for:
        minutes: 60
action:
  - variables:
      dummy: true
