---
id: "valentina_left_work_notify"
alias: "Valentina left work - notify"
initial_state: True
trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.valentina_left_work
action:
  - service: notify.telegram2rubens
    data:
      message: "Valentina sta tornando a casa"
  - service: notify.alexa_media
    data_template:
      data:
        type: tts
        method: speak
      message: "Valentina sta tornando a casa"
      target:
        - media_player.laboratorio
        - media_player.cucina
