---
id: notify_alexa_auth_required
alias: Alexa Media Player Auth required
trigger:
  platform: event
  event_type: alexa_media_relogin_required
action:
  - service: telegram_bot.send_message
    data:
      target:
        - "109669781"
      message: Alexa Media Player necessita di essere ri-autenticato! 🔑
