---
id: "29630B8D-706F-4940-A381-06A4B17A8E03"
alias: "family_goodbye"
description: "Says goodbye to the family when everybody is away"
initial_state: True
trigger:
  platform: state
  entity_id: group.family
  from: "home"
  to: "not_home"
action:
  - service: notify.catinghampalacebot
    data_template:
      message: |-
        Siete usciti tutti di casa 🏡
        A presto e{{' '}}
        {%- if (now().hour | int) < 13 -%}
          buona giornata
        {%- elif (now().hour | int) < 17 -%}
          buon pomeriggio
        {%- else -%}
          buona serata
        {%- endif -%}! 🐈
  - service: notify.catinghampalacebot
    data:
      message: "lol"
      data:
        video:
          - url: '{{((state_attr("sensor.giphy_lolcat","images") or [None]) |random).mp4 }}'
            caption: |-
              {{[
                "Non temete, ci penso io ai gattini",
                "I mici vi mandano i loro saluti!",
                "miao miao miao 🐈",
                "Ci pensiamo noi a proteggere casa 🐨 🦁 🐮",
                "E come sempre, viva i gatti 😆"
              ] | random }}
