---
id: "notify_homeassistant_startup"
alias: "Notify HomeAssistant startup"
description: "Notify HomeAssistant startup"
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  - service: telegram_bot.send_message
    data:
      entity_id:
        - "notify.telegram_bot_344202687_109669781"
      message: "HomeAssistant started 🏡"