---
id: "notify_homeassistant_shutdown"
alias: "Notify HomeAssistant shutdown"
initial_state: True
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: telegram_bot.send_message
    data:
      target:
        - "109669781"
      message: "HomeAssistant is shutting down 👋"
