---
id: "notify_homeassistant_startup"
alias: "Notify HomeAssistant startup"
description: "Notify HomeAssistant startup"
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.telegram2rubens
    data:
      message: "HomeAssistant started 🏡"
