---
id: "notify_homeassistant_shutdown"
alias: "Notify HomeAssistant shutdown"
initial_state: True
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: telegram_bot.send_message
    data:
      entity_id:
        - "notify.telegram_bot_344202687_109669781"
      message: "HomeAssistant is shutting down 👋"
