---
alias: "Update Available Notification"
description: "Send a notification when an update for HomeAssistant is available."
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: "off"
    to: "on"
action:
  - service: telegram_bot.send_message
    data:
      target:
        - "109669781"
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
