---
id: "notify_person_welcome_back"
alias: "Notify - person welcome back"
initial_state: True
trigger:
  platform: state
  entity_id:
    - person.valentina
  from: "not_home"
  to: "home"
  for: "00:04:00"
action:
  - service: notify.alexa_media
    data_template:
      data:
        type: tts
        method: speak
      message: |-
        {{ [
          "Bentornata Valentina, ci sei mancata!",
          "Ciao cara, com'è va?",
          "Guarda un po' chi si rivede!",
          "Ciao grandissima",
          "È sempre bello vederti",
          "Ti vedo radiosa quest'oggi",
          "Ué vecchia teppa, come te la passi?",
          "Come sempre è un piacere riaverti tra noi",
          "Ciao cara, come vanno le cose?"
        ] | random }}
      target:
        - media_player.laboratorio
        - media_player.cucina
