---
id: "notifier_ping"
alias: "Telegram bot that reply pong to ping"
initial_state: True
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: "/ping"
action:
  - service: telegram_bot.send_message
    data:
      target:
        - "-212768319"
      message: "pong"
