---
id: "valentina_left_work"
alias: "Valentina left work"
initial_state: True
trigger:
  - platform: zone
    entity_id: person.valentina
    zone: zone.work
    event: leave
action:
  - service: notify.telegram2rubens
    data:
      message: "Valentina sta tornando a casa"
