---
alias: IFTTT Webhook
trigger:
  platform: event
  event_type: ifttt_webhook_received
  event_data:
    action: call_service
condition:
  - condition: template
    value_template: "{{ trigger.event.data.mode is not defined }}"
action:
  service_template: "{{ trigger.event.data.service }}"
  data_template:
    entity_id: "{{ trigger.event.data.entity_id }}"
