---
id: "greenhouse_auto_humidity_power_on"
alias: "Greenhouse auto humidity power on"
initial_state: True
trigger:
  - platform: template
    value_template: '{% if (states("sensor.greenhouse_humidity")| int < (states("input_number.greenhouse_humidifier_target_humidity")|int) - 3) %}true{% endif %}'
condition:
  condition: state
  entity_id: switch.greenhouse_humidifier_mode
  state: "on"
action:
  - service: switch.turn_on
    entity_id: switch.greenhouse_humidifier_power
