---
id: "automate_kitchen_lights_on"
alias: "Automate kitchen lights ON"
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: "off"
    to: "on"
condition:
  condition: and
  conditions:
    # avoid to turn ON again after a manual switch off.
    # this lets the user exit the room.
    - condition: state
      entity_id: light.kitchen_countertop
      state: "off"
      for:
        seconds: 10

    # during the night
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:30:00"
        - condition: sun
          before: sunrise
action:
  - condition: state
    entity_id:
      - light.kitchen_countertop
      - light.kitchen_main
      - light.kitchen_hood
    state: "off"
  - service: light.turn_on
    data:
      entity_id:
        - light.kitchen_countertop
  # - service: notify.catinghampalacebot
  #   data:
  #     message: "Ho appena acceso per voi la luce in cucina 🙋‍♂️💡"
