---
id: "automate_kitchen_lights_off"
alias: "Automate kitchen lights OFF"
initial_state: True
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: light.kitchen_countertop
      state: "on"
    - condition: state
      entity_id: light.kitchen_main
      state: "on"
    - condition: state
      entity_id: light.kitchen_hood
      state: "on"
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: "on"
    to: "off"
    for: "00:10:00"
action:
  - service: light.turn_off
    entity_id:
      - light.kitchen_countertop
      - light.kitchen_main
      - light.kitchen_hood
