---
id: "automate_kitchen_lights_on"
alias: "Automate kitchen lights ON"
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: "off"
    to: "on"
condition:
  - condition: sun
    after: sunset
    after_offset: "-00:30:00"
    before: sunrise
action:
  - condition: state
    entity_id: light.kitchen_countertop
    state: "off"
  - service: light.turn_on
    data:
      entity_id:
        - light.kitchen_countertop
  - service: notify.catinghampalacebot
    data:
      message: "Ho appena acceso per voi la luce in cucina 🙋‍♂️💡"
