---
id: "automate_kitchen_lights_off"
alias: "Automate kitchen lights OFF"
initial_state: True
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: light.kitchen_countertop
      state: "on"
    - condition: state
      entity_id: light.kitchen_main
      state: "on"
    - condition: state
      entity_id: light.kitchen_hood
      state: "on"
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: "on"
    to: "off"
    for: "00:15:00" # 15 minutes
action:
  - service: light.turn_off
    entity_id: light.kitchen_countertop
  - service: light.turn_off
    entity_id: light.kitchen_main
  - service: light.turn_off
    entity_id: light.kitchen_hood
  - service: notify.catinghampalacebot
    data:
      message: "Siccome non c'è nessuno in cucina da un po' ho spento le luci 🌱🦔"
