---
id: "notify_kitchen_light_auto_off"
alias: "Notify kitchen light auto off"
initial_state: False
mode: single
trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.automate_kitchen_lights_off
action:
  - service: telegram_bot.send_message
    data:
      target:
        - "-212768319"
      message: |-
        {{ [
          "Siccome non c'è nessuno in cucina da un po' ho spento le luci 🌱🦔",
          "🌱🦔",
          "👋🦔",
          "Ho spento le luci in cucina 🌿"
        ] | random }}
  - delay: 86400 # 2 hours
