---
id: "835E634A-2E77-4A03-A802-FB082261BE19"
alias: "Kitchen sync auxiliary lights"
trigger:
  - platform: state
    entity_id: light.kitchen_hood, light.kitchen_countertop
    from: "on"
    to: "off"
  - platform: state
    entity_id: light.kitchen_hood, light.kitchen_countertop
    from: "off"
    to: "on"
action:
  service_template: "light.turn_{{ trigger.to_state.state }}"
  data_template:
    entity_id: 'light.kitchen_{% if trigger.from_state.entity_id == "light.kitchen_hood" %}countertop{% else %}hood{% endif %}'
